version: '3.9'

services:
  db:
    image: mysql
    container_name: db_collections
    environment:
      - MYSQL_DATABASE=collections
      - MYSQL_ROOT_PASSWORD=${DB_COLLECTIONS_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ../../db/collections/mysql:/var/lib/mysql
      - ../../db/collections/init.d:/docker-entrypoint-initdb.d